scraper code and results added
2020-opportunityhack-voln-internship/AnalyzingTrends pull request #3
Opened 2020-06-08 19:50 UTC by MuskanSinghal

# Sweet! You've got a Pull Request (PR)! 

# What does this PR do?

2020-06-08 20:27 UTC, claytonmgravatt requested changes
Looks fantastic, this is all very well done. Only changes requested are the merge conflicts.

2020-06-08 20:27 UTC, claytonmgravatt commented on myfile.csv
> +"1","2","3"
This file is causing a merge conflict and may need to be removed from the PR.

2020-06-08 20:27 UTC, claytonmgravatt commented on maindata.py
> +import web_scraper as webScraper
I believe this maindata.py is an older version than what's currently in the main repo and therefore is causing a merge conflict. You might want to sync up with the most recent files in the main branch and resubmit your maindata.py

2020-06-08 20:27 UTC, claytonmgravatt commented on web_scraper.py
> +    chrome_options.add_argument("--headless")
Great! I like that you're making it headless! Did this argument need to be added twice?

2020-06-22 23:12 UTC, gregv commented
@MuskanSinghal its good practice to close pull requests (by merging code) within a week - other people won’t see changes in pull requests so the faster they are merged, the better

2020-07-24 05:31 UTC, closed without merging